# Rules for Conventional Commit messages (e.g., feat: add new feature)
rules:
  type-enum:
    - 2 # Level: Error
    - always
    - [ build, chore, ci, docs, feat, fix, perf, refactor, style, test ]
