services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    volumes:
      - ./audio-node/application.yml:/opt/lavalink/application.yml
    env_file:
      - .env
    ports:
      - "${LAVALINK_PORT}:${LAVALINK_PORT}"
    networks:
      - gammatunes_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: ${LAVALINK_PORT}
    networks:
      - gammatunes_net

networks:
  gammatunes_net:
    driver: bridge
