version: "3.9"

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    env_file: .env
    ports: ["2333:2333"]
    volumes: #  ← add this block
      - ./audio-node/application.yml:/opt/Lavalink/application.yml:ro
    networks: [gammatunes_net]

  app:
    build: .
    depends_on: [lavalink]
    env_file: .env
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      LAVALINK_PORT: ${LAVALINK_PORT}
      LAVALINK_USER_ID: ${LAVALINK_USER_ID}
      LAVALINK_NODES_0_URI: ws://lavalink:${LAVALINK_PORT}
      LAVALINK_NODES_0_PASSWORD: ${LAVALINK_NODES_0_PASSWORD}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    ports: ["8080:8080"]
    networks: [gammatunes_net]

networks:
  gammatunes_net:
    driver: bridge
