version: "3.8"

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    volumes:
      - ./audio-node/application.yml:/opt/lavalink/application.yml
    env_file:
      - .env
    ports:
      # Uses the variable from the .env file
      - "${LAVALINK_PORT}:${LAVALINK_PORT}"
    networks:
      - gammatunes_net
    healthcheck:
      # Also uses the variable
      test: ["CMD", "curl", "-f", "http://localhost:${LAVALINK_PORT}/v4/info"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      lavalink:
        condition: service_healthy
    env_file:
      - .env
    ports:
      # Uses the variable from the .env file
      - "${BACKEND_PORT}:8080"
    environment:
      # These are internal to the Docker network and can remain hardcoded
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: ${LAVALINK_PORT}
    networks:
      - gammatunes_net

networks:
  gammatunes_net:
    driver: bridge
