version: "3.8"

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4       # ✅ latest v4
    container_name: lavalink
    volumes:
      - ./audio-node/application.yml:/opt/lavalink/application.yml
    environment:
      LAVALINK_SERVER_PASSWORD: ${LAVALINK_PASSWORD}
      SERVER_PORT: 2333
    ports: ["2333:2333"]
    networks: [ gammatunes_net ]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      lavalink:           # 👉 wait for Lavalink socket to open
        condition: service_started
    ports: ["8080:8080"]
    environment:
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: 2333
      LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
    networks: [ gammatunes_net ]

  bot:
    build:
      context: .
      dockerfile: bot-jda/Dockerfile
    depends_on:
      - backend # The bot should wait for the backend to be available
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      BACKEND_API_URL: "http://backend:8080"
    networks: [ gammatunes_net ]

networks:
  gammatunes_net:
    driver: bridge
