discord.bot.token=${DISCORD_BOT_TOKEN}
logging.level.root=DEBUG
gamma.bot.player.panel.min-refresh-gap-ms=0

lavalink.user-id=${LAVALINK_USER_ID}
lavalink.nodes[0].name=main
lavalink.nodes[0].uri=ws://localhost:2333
lavalink.nodes[0].password=${LAVALINK_NODES_0_PASSWORD}

spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
spotify.redirect-uri=${SPOTIFY_REDIRECT_URI}
