# ./audio-node/application.yml  (corrected)
server:                # <── HTTP server of Lavalink itself
  port: 2333           # WebSocket & REST will now bind to 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      http: true
    player-update-interval: 5
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

logging:
  level:
    root: INFO
    lavalink: INFO
