server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "${LAVALINK_PASSWORD}" # Uses the environment variable
    sources:
      youtube: true
      soundcloud: true
    player-update-interval: 5 # How often to update player status (in seconds)

logging:
  level:
    root: INFO
    lavalink: INFO
