management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: backend
  main:
    web-application-type: reactive
    banner-mode: "off"
