name: Gamma Tunes CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ────────────────────────────────────────────────────────────────
  # 1) BACKEND  •  UNIT + INTEGRATION (Testcontainers) TESTS
  # ────────────────────────────────────────────────────────────────
  backend-tests:
    name: Backend • Gradle tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle               # caches ~/.gradle and ~/.m2

      - name: ./gradlew clean test
        run: ./gradlew --no-daemon clean test

  # ────────────────────────────────────────────────────────────────
  # 3) BOT-PYTHON  (placeholder – non-blocking)
  # ────────────────────────────────────────────────────────────────
#  bot-python:
#    name: Bot-Python (placeholder)
#    runs-on: ubuntu-latest
#    continue-on-error: true
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: "3.12"
#
#      - name: TODO – add pytest
#        run: |
#          cd bot-python
#          echo "TODO: pip install -r requirements.txt && pytest"

  # ────────────────────────────────────────────────────────────────
  # 4) FRONTEND  (placeholder – non-blocking)
  # ────────────────────────────────────────────────────────────────
#  frontend:
#    name: Frontend (placeholder)
#    runs-on: ubuntu-latest
#    continue-on-error: true
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: "20"
#          cache: npm
#          cache-dependency-path: frontend/package-lock.json
#
#      - name: TODO – add build script
#        run: |
#          cd frontend
#          echo "TODO: npm ci && npm run build"
